NAME = run

SRC =	ft_atoi.c \
		count.c \
		creat_node_map.c \
		creat_map.c \
		main.c \
		slove.c

CC =	cc

CFLAGS = -Wall -Wextra -Werror

all : $(NAME)

$(NAME):
	$(CC) $(CFLAGS) $(SRC) -o $(NAME)

clean:

fclean:
		rm -f $(NAME)

re: fclean all
